### PR TITLE
Add possibility to calibrate joints in a given order

### PR DESCRIPTION
**Pull request by paLeziart**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

This PR lets the possibility to calibrate joints in a given order by using new fields `calib_order` and `calib_pos` in the yaml configuration file.
These fields can take for instance the following value:
```
calib_order: [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
calib_pos: [
        0.0,  1.2, -2.4,
        0.0,  1.2, -2.4,
        0.0, -1.2,  2.4,
        0.0, -1.2,  2.4
]
```

Actuators with the lowest order value are calibrated first, so in this case the HFE and Knee joints of the four legs will look for their index first while the HAA are immobile. Once they have found their index, they go into waiting position (here +-1.2rad and +-2.4 rad respectively). Then, the four HAA joints look for their index while the legs are folded up.

This feature can be useful when launching the robot controller while it is on its stand as the legs can impact the stand if the HAA joints move with the leg extended (the behaviour depends on index position offsets values).

<br>*Solo 12 quadruped on its stand.*<br>

If all `calib_order` are set to 0, then it just will behave like before by calibrating all joints at the same time.

## How I Tested

It was sucessfully tested on our Solo 12 quadruped.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ ] All new functions/classes are documented and existing documentation is updated according to changes.
- [ ] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by jviereck** [comment]
Hi @paLeziart, thank you for this PR.

I am not sure if this is needed. Have you tried to switch the orientation of the motors while they are calibrating? For instance, we run some of the motors forwards and some backwards and this way we always make sure to avoid hitting the stand during calibration. What you propose here is working but more complex.

In addition, there is a problem: As some of the joints are not actuated, they might move over the index by accident when the other joints are moving. This might lead to a wrong calibration.

What do you think?

\cc @luator

**Comment by luator** [comment]
I haven't looked at the code in detail but some general thought: There might be easier solutions for Solo on the stand but in general it's a feature that might be nice to have.  For the TriFinger robots I once considered implementing something similar to reduce the risk of the fingers blocking each other if they are in some unknown initial position.  The whole initialisation is a bit different there, though, as the joints go to the end-stop and thus have to move much more than on Solo.

**Comment by paLeziart** [comment]
Thank you for your quick answer! What do you mean by changing the orientation of motors while they are calibrating? Changing the calibration mode from POS to NEG or NEG to POS if you see that one of the motors is hitting the stand? We are using AUTO calibration mode.

Yes you are right, the other joints might move over their index. I don't have the code well-enough in mind to know if that can lead to a wrong calibration. The fact that the index has been seen will be kept in memory by the lower level code of masterboard-sdk right?

**Comment by jviereck** [comment]
> What do you mean by changing the orientation of motors while they are calibrating? Changing the calibration mode from POS to NEG or NEG to POS if you see that one of the motors is hitting the stand? We are using AUTO calibration mode.

Yes, exactly. We set them to NEG and POS to get the calibration working always in certain directions. This way we avoid hitting the teststand.

> Yes you are right, the other joints might move over their index. I don't have the code well-enough in mind to know if that can lead to a wrong calibration. The fact that the index has been seen will be kept in memory by the lower level code of masterboard-sdk right?

I think it's the low level of the udriver board. In any case, we don't have the ability to reset the calibration index. So if we visit the first one wrongly, then there is no way to reset it at this current point.

**Comment by thomasfla** [comment]
Hi, 
I'm jumping in as I would also like to see this merged. 

@jviereck imposing a direction for index search is a workaround, but it reduces the robustness if the index is not close to 180deg from the zero pose. Also, for different robots, this is a nice feature to have. This shouldn't break backward compatibility.

We have been using this code for quite some time, here is what the calibration looks like on our solo12:
https://youtu.be/zV6LLB7yn4o

I would like that we get back in sync with all our low level code. 
What do you think? 

Best,
Thomas.

**Comment by thomasfla** [comment]
Thanks ! We can also merge #14 then

**Pull request merged**
